In [8]:
import numpy as np
import heapq

In [2]:
def NSF():
    topology = np.array([[0, 2100, 3000, np.inf, np.inf, np.inf, np.inf, 4800, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf],
                          [2100, 0, 1200, 1500, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf],
                          [3000, 1200, 0, np.inf, np.inf, 3600, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf],
                          [np.inf, 1500, np.inf, 0, 1200, np.inf, np.inf, np.inf, np.inf, np.inf, 3900, np.inf, np.inf, np.inf],
                          [np.inf, np.inf, np.inf, 1200, 0, 2400, 1200, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf],
                          [np.inf, np.inf, 3600, np.inf, 2400, 0, np.inf, np.inf, np.inf, 2100, np.inf, np.inf, np.inf, 3600],
                          [np.inf, np.inf, np.inf, np.inf, 1200, np.inf, 0, 1500, np.inf, 2700, np.inf, np.inf, np.inf, np.inf],
                          [4800, np.inf, np.inf, np.inf, np.inf, np.inf, 1500, 0, 1500, np.inf, np.inf, np.inf, np.inf, np.inf],
                          [np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 1500, 0, 1500, np.inf, 600, 600, np.inf],
                          [np.inf, np.inf, np.inf, np.inf, np.inf, 2100, 2700, np.inf, 1500, 0, np.inf, np.inf, np.inf, np.inf],
                          [np.inf, np.inf, np.inf, 3900, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 0, 1200, 1500, np.inf],
                          [np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 600, np.inf, 1200, 0, np.inf, 600],
                          [np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 600, np.inf, 1500, np.inf, 0, 300],
                          [np.inf, np.inf, np.inf, np.inf, np.inf, 3600, np.inf, np.inf, np.inf, np.inf, np.inf, 600, 300, 0]])
    
    topology = topology / 2
    return topology

In [3]:
# Call the function to get the topology matrix
topology_matrix = NSF()

In [4]:
def topology_link(W):
    num_nodes = len(W)
    link = np.zeros((num_nodes, num_nodes), dtype=int)
    linksum = 0
    
    for i in range(num_nodes):
        for j in range(num_nodes):
            if W[i, j] != 0 and W[i, j] != np.inf:
                linksum += 1
                link[i, j] = linksum
    
    return link, linksum

In [5]:
W = topology_matrix
link_matrix, total_links = topology_link(W)
print("Link Matrix:")
print(link_matrix)
print("Total Number of Links:", total_links)

Link Matrix:
[[ 0  1  2  0  0  0  0  3  0  0  0  0  0  0]
 [ 4  0  5  6  0  0  0  0  0  0  0  0  0  0]
 [ 7  8  0  0  0  9  0  0  0  0  0  0  0  0]
 [ 0 10  0  0 11  0  0  0  0  0 12  0  0  0]
 [ 0  0  0 13  0 14 15  0  0  0  0  0  0  0]
 [ 0  0 16  0 17  0  0  0  0 18  0  0  0 19]
 [ 0  0  0  0 20  0  0 21  0 22  0  0  0  0]
 [23  0  0  0  0  0 24  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 26  0 27  0 28 29  0]
 [ 0  0  0  0  0 30 31  0 32  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0  0 34 35  0]
 [ 0  0  0  0  0  0  0  0 36  0 37  0  0 38]
 [ 0  0  0  0  0  0  0  0 39  0 40  0  0 41]
 [ 0  0  0  0  0 42  0  0  0  0  0 43 44  0]]
Total Number of Links: 44


In [6]:
def cost_239():
    num_nodes = 11
    topology = np.ones((num_nodes, num_nodes)) * np.inf
    
    for ii in range(num_nodes):
        topology[ii, ii] = 0
    
    # ii=1
    topology[0, 1] = 450 * 2
    topology[0, 2] = 390 * 2
    topology[0, 3] = 550 * 2
    topology[0, 7] = 1310 * 2
    
    # ii=2
    topology[1, 2] = 300 * 2
    topology[1, 4] = 400 * 2
    topology[1, 5] = 600 * 2
    topology[1, 6] = 820 * 2
    topology[1, 8] = 1090 * 2
    
    # ii=3
    topology[2, 3] = 210 * 2
    topology[2, 4] = 220 * 2
    topology[2, 6] = 930 * 2
    
    # ii=4
    topology[3, 4] = 390 * 2
    topology[3, 7] = 760 * 2
    topology[3, 8] = 660 * 2
    
    # ii=5
    topology[4, 5] = 350 * 2
    topology[4, 9] = 730 * 2
    
    # ii=6
    topology[5, 6] = 320 * 2
    topology[5, 9] = 565 * 2
    topology[5, 10] = 730 * 2
    
    # ii=7
    topology[6, 10] = 820 * 2
    
    # ii=8
    topology[7, 8] = 390 * 2
    topology[7, 9] = 740 * 2
    
    # ii=9
    topology[8, 9] = 340 * 2
    topology[8, 10] = 660 * 2
    
    # ii=10
    topology[9, 10] = 320 * 2
    
    for ii in range(10):
        for jj in range(ii + 1, 11):
            topology[jj, ii] = topology[ii, jj]
    
    return topology

In [7]:
topology_cost_matrix = cost_239()
print(topology_cost_matrix)

[[   0.  900.  780. 1100.   inf   inf   inf 2620.   inf   inf   inf]
 [ 900.    0.  600.   inf  800. 1200. 1640.   inf 2180.   inf   inf]
 [ 780.  600.    0.  420.  440.   inf 1860.   inf   inf   inf   inf]
 [1100.   inf  420.    0.  780.   inf   inf 1520. 1320.   inf   inf]
 [  inf  800.  440.  780.    0.  700.   inf   inf   inf 1460.   inf]
 [  inf 1200.   inf   inf  700.    0.  640.   inf   inf 1130. 1460.]
 [  inf 1640. 1860.   inf   inf  640.    0.   inf   inf   inf 1640.]
 [2620.   inf   inf 1520.   inf   inf   inf    0.  780. 1480.   inf]
 [  inf 2180.   inf 1320.   inf   inf   inf  780.    0.  680. 1320.]
 [  inf   inf   inf   inf 1460. 1130.   inf 1480.  680.    0.  640.]
 [  inf   inf   inf   inf   inf 1460. 1640.   inf 1320.  640.    0.]]


In [9]:
def dijkstra(netCostMatrix, source, destination):
    n = len(netCostMatrix)
    distance = [np.inf] * n
    parent = [None] * n
    visited = [False] * n
    
    distance[source] = 0
    priority_queue = [(0, source)]
    
    while priority_queue:
        dist_u, u = heapq.heappop(priority_queue)
        
        if visited[u]:
            continue
        
        visited[u] = True
        
        for v in range(n):
            if not visited[v] and netCostMatrix[u, v] != np.inf:
                new_dist = dist_u + netCostMatrix[u, v]
                if new_dist < distance[v]:
                    distance[v] = new_dist
                    parent[v] = u
                    heapq.heappush(priority_queue, (new_dist, v))
    
    shortest_path = []
    total_cost = distance[destination]
    
    if parent[destination] is not None:
        current_node = destination
        while current_node != source:
            shortest_path.append(current_node)
            current_node = parent[current_node]
        shortest_path.append(source)
        shortest_path.reverse()
    
    return shortest_path, total_cost


In [10]:
netCostMatrix = topology_cost_matrix
source_node = 0
destination_node = 10

shortest_path, total_cost = dijkstra(netCostMatrix, source_node, destination_node)
print("Shortest Path:", shortest_path)
print("Total Cost:", total_cost)

Shortest Path: [0, 2, 4, 9, 10]
Total Cost: 3320.0


In [11]:
def cal_len(path, topo):
    path_length = 0
    for i in range(len(path) - 1):
        if topo[path[i], path[i+1]] != np.inf:
            path_length += topo[path[i], path[i+1]]
        else:
            return np.inf  # Return inf if any link is unavailable
    return path_length

In [12]:
path = [0, 2, 4, 9, 10]  # Example path indices (replace with your path)
length = cal_len(path, topology_matrix)
print("Path Length:", length)

Path Length: inf


In [13]:
def calclink(p, link):
    path_link = []
    for i in range(len(p) - 1):
        a = p[i]
        b = p[i + 1]
        path_link.append(link[a][b])
    return path_link

In [14]:
path = [0, 2, 4, 9, 10]  # Example path indices (replace with your path)
path_links = calclink(path, topology_matrix)
print("Path Links:", path_links)

Path Links: [1500.0, inf, inf, inf]
